/*
    Copyright 2017 Zheyong Fan and GPUMD development team
    This file is part of GPUMD.
    GPUMD is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    GPUMD is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with GPUMD.  If not, see <http://www.gnu.org/licenses/>.
*/

/*----------------------------------------------------------------------------80
A minimal standalone test driver for NepGpuModel.
It evaluates a tiny two-atom system using a user-specified NEP potential file
and prints total energy, virial, and per-atom forces.
------------------------------------------------------------------------------*/

#include "nep_gpu_model.cuh"

#include "utilities/error.cuh"
#include "utilities/gpu_macro.cuh"

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <vector>

int main(int argc, char* argv[])
{
  if (argc < 2) {
    std::printf("Usage: %s nep_potential_file\n", argv[0]);
    return EXIT_FAILURE;
  }

  const char* potential_file = argv[1];

  // Ensure a run.in exists so that NEP::initialize_dftd3() in src/force/nep.cu
  // does not fail with "Cannot open run.in.". For testing we do not use DFTD3,
  // so an empty placeholder file is sufficient.
  {
    std::ifstream run_in("run.in");
    if (!run_in.is_open()) {
      std::ofstream out("run.in");
      if (!out.is_open()) {
        std::printf("Error: cannot create dummy run.in in current directory.\n");
        return EXIT_FAILURE;
      }
      out << "# Dummy run.in generated by main_nep_gpu_test.\n";
      out.close();
      std::printf("Created dummy run.in for test.\n");
    }
  }

  // For this simple test, use a small maximum atom count.
  const int max_atoms = 16;

  // Select GPU-0 by default.
  NepGpuModel model(potential_file, max_atoms);
  model.set_device(0);

  std::printf("NEP_GPU test\n");
  std::printf("  potential file : %s\n", potential_file);
  std::printf("  rc_radial      : %g\n", static_cast<double>(model.cutoff()));
  std::printf("  num_types      : %d\n", model.num_types());

  // Build a simple two-atom system in a cubic box.
  const int natoms = 2;
  int type_host[natoms] = {0, 0}; // both atoms use NEP type 0

  // Positions in Cartesian coordinates (Angstrom).
  // Atom 0 at origin, atom 1 displaced along x.
  double xyz_host[3 * natoms] = {
    0.0, 0.0, 0.0,
    1.5, 0.0, 0.0};

  // Simple cubic box of length 20 Angstrom along each axis.
  double h[9] = {
    20.0, 0.0, 0.0,
    0.0, 20.0, 0.0,
    0.0, 0.0, 20.0};

  NepGpuSystem sys;
  sys.natoms = natoms;
  sys.type = type_host;
  sys.xyz = xyz_host;
  for (int i = 0; i < 9; ++i) {
    sys.h[i] = h[i];
  }
  sys.pbc_x = 1;
  sys.pbc_y = 1;
  sys.pbc_z = 1;

  NepGpuResult res;
  std::vector<double> f_host(3 * natoms);
  std::vector<double> eatom_host(natoms);
  std::vector<double> vatom_host(6 * natoms);

  res.f = f_host.data();
  res.eatom = eatom_host.data();
  res.vatom = vatom_host.data();

  model.compute(sys, res);

  std::printf("\nResults:\n");
  std::printf("  Total energy (this rank): % .10e\n", res.eng);
  std::printf("  Virial (xx,yy,zz,xy,yz,zx):\n");
  std::printf("    % .10e % .10e % .10e % .10e % .10e % .10e\n",
              res.virial[0],
              res.virial[1],
              res.virial[2],
              res.virial[3],
              res.virial[4],
              res.virial[5]);

  std::printf("\nPer-atom quantities:\n");
  for (int i = 0; i < natoms; ++i) {
    const double fx = f_host[3 * i + 0];
    const double fy = f_host[3 * i + 1];
    const double fz = f_host[3 * i + 2];
    std::printf("  Atom %d:\n", i);
    std::printf("    type       = %d\n", type_host[i]);
    std::printf("    position   = (% .6f, % .6f, % .6f)\n",
                xyz_host[3 * i + 0],
                xyz_host[3 * i + 1],
                xyz_host[3 * i + 2]);
    std::printf("    force      = (% .6e, % .6e, % .6e)\n", fx, fy, fz);
    std::printf("    energy     = % .6e\n", eatom_host[i]);
    std::printf("    virial(xx,yy,zz,xy,yz,zx) = ");
    const int idx = 6 * i;
    std::printf("% .6e % .6e % .6e % .6e % .6e % .6e\n",
                vatom_host[idx + 0],
                vatom_host[idx + 1],
                vatom_host[idx + 2],
                vatom_host[idx + 3],
                vatom_host[idx + 4],
                vatom_host[idx + 5]);
  }

  // Also dump the configuration to an extended XYZ file (nep_gpu_test.xyz)
  // so that it can be used to cross-check with other NEP tools.
  {
    std::FILE* fid = std::fopen("nep_gpu_test.xyz", "w");
    if (fid) {
      // Line 1: number of atoms.
      std::fprintf(fid, "%d\n", natoms);

      // Line 2: EXYZ header with box and basic properties.
      // Here we do not output time/energy/stress; only the essentials needed
      // to reuse the structure: PBC, Lattice and Properties.
      std::fprintf(
        fid,
        "pbc=\"T T T\" "
        "Lattice=\"%.8f %.8f %.8f %.8f %.8f %.8f %.8f %.8f %.8f\" "
        "Properties=species:S:1:pos:R:3:forces:R:3:energy_atom:R:1\n",
        h[0],
        h[3],
        h[6],
        h[1],
        h[4],
        h[7],
        h[2],
        h[5],
        h[8]);

      // Atom lines: species x y z fx fy fz e_atom
      // Species is set to a generic symbol "X"; in practice you should replace
      // it with the real element used in the NEP potential.
      for (int i = 0; i < natoms; ++i) {
        const double x = xyz_host[3 * i + 0];
        const double y = xyz_host[3 * i + 1];
        const double z = xyz_host[3 * i + 2];
        const double fx = f_host[3 * i + 0];
        const double fy = f_host[3 * i + 1];
        const double fz = f_host[3 * i + 2];
        const double ea = eatom_host[i];
        std::fprintf(
          fid,
          "X %.8f %.8f %.8f %.8e %.8e %.8e %.8e\n",
          x,
          y,
          z,
          fx,
          fy,
          fz,
          ea);
      }

      std::fclose(fid);
      std::printf("\nConfiguration written to nep_gpu_test.xyz (extended XYZ format).\n");
    } else {
      std::printf("\nWarning: failed to open nep_gpu_test.xyz for writing.\n");
    }
  }

  return EXIT_SUCCESS;
}
